### ISSUE TITLE
mathptmx导致\mathbf等命令失效

### ISSUE THREAD

**Issue by yizx6** [yuhldr/LZUThesis2020#15]
您好：
mathptmx貌似跟amsmath有冲突，使得后者的加粗命令失效。我使用newtxmath替代mathptmx后，数学公式的字体变成了times new roman，但正文中的英文字体不知如何修改，作者可否帮忙看看？

**Comment by yuhldr** [comment]
1. 本科的还是研究生模板
2. 具体问题部分的latex代码发一下

**Comment by yizx6** [comment]
1、研究生模板
2、有问题的代码如下：
`\textbf{\textit{W}} \\
\boldsymbol{W}\\`
第一行是斜体加粗，而第二行只有斜体效果。理论上两者具有相同的效果

**Comment by yizx6** [comment]
还想请教个问题：研究生参考文献的模板怎么改成lzubib.bst了，官网上的要求是7714（2015），直接用宏包不是挺好的嘛

**Comment by yuhldr** [comment]
> 还想请教个问题：研究生参考文献的模板怎么改成lzubib.bst了，官网上的要求是7714（2015），直接用宏包不是挺好的嘛

这个我修改的不合适，查找以后，已经恢复原来的

**Comment by yuhldr** [comment]
> 1、研究生模板 2、有问题的代码如下： `\textbf{\textit{W}} \\ \boldsymbol{W}\\` 第一行是斜体加粗，而第二行只有斜体效果。理论上两者具有相同的效果

因为确实了 `bm` 软件包，已经引入，使用方法，如下

https://github.com/yuhldr/LZUThesis2020/blob/3991667f047fd581654dc90242fa1de9e0a5add7/template-PgD%26PhD.tex#L243-L250

**Comment by yizx6** [comment]
> > 还想请教个问题：研究生参考文献的模板怎么改成lzubib.bst了，官网上的要求是7714（2015），直接用宏包不是挺好的嘛
> 
> 这个我修改的不合适，查找以后，已经恢复原来的

好的，谢谢！

**Comment by yizx6** [comment]
> > 1、研究生模板 2、有问题的代码如下： `\textbf{\textit{W}} \\ \boldsymbol{W}\\` 第一行是斜体加粗，而第二行只有斜体效果。理论上两者具有相同的效果
> 
> 因为缺少了 `bm` 软件包，已经引入，使用方法，如下
> 
> https://github.com/yuhldr/LZUThesis2020/blob/3991667f047fd581654dc90242fa1de9e0a5add7/template-PgD%26PhD.tex#L243-L250


bm包的效果貌似不是特别好。在加粗的同时，会使字母变宽。作者能否看一下这个包newtxmath，这个包可以把公式字体改成times new roman，但是正文无法处理。
![屏幕截图 2023-02-23 090633](https://user-images.githubusercontent.com/18640552/220800018-9a0bdf24-2d6d-48b8-90fc-64bebb446602.png)

**Comment by yuhldr** [comment]
已修改，
```tex
\RequirePackage{mathptmx, newtxmath}
```
这样正文就没问题了

三者区别，可以看这里的注释
https://github.com/yuhldr/LZUThesis2020/blob/ed0f109fca96816f6c618ced7995ac575f62aced/LZUThesis-PgD%26PhD.cls#L186-L212

**Comment by tygkking** [comment]
> > 还想请教个问题：研究生参考文献的模板怎么改成lzubib.bst了，官网上的要求是7714（2015），直接用宏包不是挺好的嘛
> 
> 这个我修改的不合适，查找以后，已经恢复原来的

你好，请问研究生模板里最终还是使用默认的 gbt7714-numerical 是最优的吗？我看到今天提交的版本中先将参考文献的模板修改为lzubib，但在之后的提交版本中又撤销了这个更改。

**Comment by yuhldr** [comment]
> > > 还想请教个问题：研究生参考文献的模板怎么改成lzubib.bst了，官网上的要求是7714（2015），直接用宏包不是挺好的嘛
> > 
> > 
> > 这个我修改的不合适，查找以后，已经恢复原来的
> 
> 你好，请问研究生模板里最终还是使用默认的 gbt7714-numerical 是最优的吗？我看到今天提交的版本中先将参考文献的模板修改为lzubib，但在之后的提交版本中又撤销了这个更改。

对的，看这里 [兰州大学研究生学位论文写作参考规范](https://ge.lzu.edu.cn/xueweishouyu/guizhangzhidu/lunwenguanli/2020/1223/158947.html)

**Comment by tygkking** [comment]
> 

好的，谢谢！
