### ISSUE TITLE
四级标题效果和学校要求不一致

### ISSUE THREAD

**Issue by yizx6** [yuhldr/LZUThesis2020#17]
```tex
\subsubsection{四级标题}
```
效果如下图，个人觉得加粗的效果不是特别好。
![image](https://user-images.githubusercontent.com/18640552/224063307-044721bd-b226-4fe6-8588-22c5e5fa7dd9.png)
学校最新版格式的要求如下图：
![image](https://user-images.githubusercontent.com/18640552/224063639-2788c4e6-958d-4cfb-830b-237fcfd328f2.png)

大佬是否可以看下这个问题？

**Comment by yizx6** [comment]
hello，您有空吗？

**Comment by yuhldr** [comment]
与[论文要求](https://ge.lzu.edu.cn/xueweishouyu/guizhangzhidu/lunwenguanli/2020/1223/158947.html)没有冲突，加粗效果明天我试试看，我记得linux和windows上编译效果不一样

<img width="777" alt="image" src="https://user-images.githubusercontent.com/25719023/224785761-0772c561-da0c-4a23-90f4-09bb0b280fba.png">

**Comment by yuhldr** [comment]
效果上好像也没问题，黑体加粗就是这么丑。。。。

**Comment by yizx6** [comment]
要求貌似没说到四级标题哎，只对三级标题进行了要求。但由于章标题的存在，标题深度不太够用了

**Comment by yizx6** [comment]
四级标题宋体加粗看起来有点怪哎。个人建议还原（黑体，首行缩进两个汉字符）。
<img width="380" alt="截屏2023-04-04 21 18 41" src="https://user-images.githubusercontent.com/18640552/229806348-b2fb3eb0-ae73-49c2-a819-7f126e4321bf.png">

**Comment by yuhldr** [comment]
因为学校里面没要求，我给删了，好像应该加回去，字体可以改一下，首行缩进就不用了，因为学校给的pdf，前几级标题都没缩进

**Comment by yizx6** [comment]
OK
