### ISSUE TITLE
研究生版本。footskip要求。

### ISSUE THREAD

**Issue by LZU-Machine-learning-theory** [yuhldr/LZUThesis2020#21]
学校的要求的：
页边距一般要求：上边距 3cm、下边距为 2.54cm,左右为 3.17cm,页眉页脚为 2.0cm；
cls实现的：
`\RequirePackage[top=3cm, bottom=2.54cm,outer=3.17cm, inner=3.17cm, headheight=2.0cm, footskip=2.0cm, heightrounded]{geometry}`

但是word里面的页脚是从下往上（纸的下边到文字区），而latex里面的footskip不是直接的页脚，是页码到文字区的距离。
![image](https://user-images.githubusercontent.com/118443686/229830788-f6224a40-98e2-4f94-b243-455dc8855583.png)

按照cls里面的实现，会出现页码紧贴文字的现象

**Comment by yuhldr** [comment]
你指的是不是现在tex的页码紧贴页面下边界？这个和学校模板差别挺大，我晚上查查

**Comment by LZU-Machine-learning-theory** [comment]
是的

**Comment by yuhldr** [comment]
这样是不是就合适了

```tex
\RequirePackage[top=3cm, bottom=2.54cm,outer=3.17cm, inner=3.17cm, headheight=1cm, footskip=0.54cm]{geometry}
````

**Comment by LaaaaaaaaiFe** [comment]
> 这样是不是就合适了
> 
> ```
> \RequirePackage[top=3cm, bottom=2.54cm,outer=3.17cm, inner=3.17cm, headheight=1cm, footskip=0.54cm]{geometry}
> ```

我在使用你刚刚更新的模板的时候，第一页会出现：
![image](https://user-images.githubusercontent.com/72681215/230704116-fa76eb3f-5b5b-43d8-86d0-745c2e1c60c5.png)
同时目录、参考文献等引用均无法正常显示。

当我把.cls中
> \RequirePackage[top=3cm, bottom=2.54cm,outer=3.17cm, inner=3.17cm, headheight=1cm, footskip=0.54cm heightrounded]{geometry}

`heightrounded`删掉之后，目录、参考文献等引用恢复正常了，第一页也不再有空白页了，但论文封面消失了：
![image](https://user-images.githubusercontent.com/72681215/230704186-3b4b6515-37e1-4300-a2b6-a62ff968c4bb.png)

请问是版本的问题么（我的texlive是昨天刚刚更新的最新版）。

**Comment by yuhldr** [comment]
> > 这样是不是就合适了
> > ```
> > \RequirePackage[top=3cm, bottom=2.54cm,outer=3.17cm, inner=3.17cm, headheight=1cm, footskip=0.54cm]{geometry}
> > ```
> 
> 我在使用你刚刚更新的模板的时候，第一页会出现： ![image](https://user-images.githubusercontent.com/72681215/230704116-fa76eb3f-5b5b-43d8-86d0-745c2e1c60c5.png) 同时目录、参考文献等引用均无法正常显示。
> 
> 当我把.cls中
> 
> > \RequirePackage[top=3cm, bottom=2.54cm,outer=3.17cm, inner=3.17cm, headheight=1cm, footskip=0.54cm heightrounded]{geometry}
> 
> `heightrounded`删掉之后，目录、参考文献等引用恢复正常了，第一页也不再有空白页了，但论文封面消失了： ![image](https://user-images.githubusercontent.com/72681215/230704186-3b4b6515-37e1-4300-a2b6-a62ff968c4bb.png)
> 
> 请问是版本的问题么（我的texlive是昨天刚刚更新的最新版）。
下载新的试一下，之前那次提交少了个逗号

**Comment by yizx6** [comment]
目前这个距离好像太小了。
<img width="322" alt="image" src="https://github.com/yuhldr/LZUThesis2020/assets/18640552/d3f99a81-2983-48b7-8e85-19e0c990094a">

**Comment by yuhldr** [comment]
> 目前这个距离好像太小了。好像也不是每页都距离这么小，不知道是什么bug。 <img alt="image" width="322" src="https://user-images.githubusercontent.com/18640552/239739729-b16c0623-a738-4c6f-a8da-8310d7b32c96.png">

我这边看到的没有这么小，你看一下这个项目的原始 pdf 文件正文里的

**Comment by yuhldr** [comment]
摘要我刚才也测试了，也是正常的

**Comment by yizx6** [comment]
这问有类似这种情况。
<img width="317" alt="image" src="https://github.com/yuhldr/LZUThesis2020/assets/18640552/e53b528e-2243-41d7-bfb0-a363f679b699">
这个距离好像是正常的。
<img width="321" alt="image" src="https://github.com/yuhldr/LZUThesis2020/assets/18640552/bfd9cb84-ff68-4eb2-9419-da4e0739e460">

**Comment by yizx6** [comment]
> 摘要我刚才也测试了，也是正常的

这测试的摘要恰好是最后一行。
