### ISSUE TITLE
疑似规范性bug：目录页有罗马数字页码；Windows无法git clone

### ISSUE THREAD

**Issue by JerryOops** [yuhldr/LZUThesis2020#23]
背景：本科生模板，texlive2020 + VS Code + 四步走 + 最新版本直接编译

本科毕业论文（设计）管理细则quote：
“页码。页脚居中排，字体为宋体，五号。【封面、目录不编排页码】，中英文摘要页用罗马数字单独连续编号....”

问题1：当目录总共为两页时，其中第1页底端存在罗马数字页码，疑似与规范相悖：
![Inked目录页码](https://user-images.githubusercontent.com/53827342/233300246-ca6ea125-cc0c-449c-b176-da7a6fb37f32.jpg)

问题2：Windows环境下无法直接git clone：
![image](https://user-images.githubusercontent.com/53827342/233300619-442fa55e-26d3-4571-b571-ee7d7bbfd890.png)

**Comment by yuhldr** [comment]
看[常见问题](https://github.com/yuhldr/LZUThesis2020/blob/master/md/QA.md)最后一句，而且给出的示例是没有页码的

**Comment by yuhldr** [comment]
之前我理解错误，已经修复：[看这里](https://gitee.com/yuhldr/LZUThesis2020/issues/I73ZGA)
