### ISSUE TITLE
本科生cls文件中缺少remark的newtheorem命令

### ISSUE THREAD

**Issue by mutto00** [yuhldr/LZUThesis2020#24]
在cls文件中直接添加上是否就可以不用再进行其他操作了

**Comment by mutto00** [comment]
在添加到cls中后不小心点击xelatex编译了cls文件报了错，但是正文可以正常编译，应该不会对正文产生影响吧，是否还需要别的处理补救

**Comment by yuhldr** [comment]
直接如下在tex中使用即可，不许需要其他操作
```tex
\begin{theorem}[均值不等式]
    设$A,B$是两个实数, 则$2AB\leq 2 A^2+B^2$.
\end{theorem}
```

**Comment by yuhldr** [comment]
你具体用的是什么？我好像没太看懂，附上具体的tex代码

**Comment by mutto00** [comment]
就是在正文中直接
\begin{remark}
aa
\end{remark}
会编译不成功，因为我看了以下cls文件中没有关于remark的newtheorem的命令，只有theorem、corollary、definition这些
