### ISSUE TITLE
请问加减号怎么处理，总是乱码，写了\pm 谢谢

### ISSUE THREAD

**Issue by liyz-shanshang** [yuhldr/LZUThesis2020#29]
请问加减号怎么处理，总是乱码，写了\pm 谢谢。

**Comment by yuhldr** [comment]
已经测试，xelatex编译没有问题，请自己核查
![image](https://github.com/yuhldr/LZUThesis2020/assets/25719023/97055612-4c06-48f4-80ac-c5df57050bd6)
