### ISSUE TITLE
目录第二页出现页眉？

### ISSUE THREAD

**Issue by accelia20** [yuhldr/LZUThesis2020#37]
使用模板生成毕业论文后目录的第二页似乎出现了页眉，根据老师的说法这似乎是不符合规范的（只有正文部分才应该有页眉）。

**Comment by yuhldr** [comment]
没有这个问题，大概率是因为你把`\mainmatter`这一行写错位置了：
![图片](https://github.com/user-attachments/assets/38742396-db93-4922-b462-69ffe7a6a02f)
