### ISSUE TITLE
中英文混合的参考文献显示不对

### ISSUE THREAD

**Issue by ffdm12138** [yuhldr/LZUThesis2020#40]
![image](https://github.com/user-attachments/assets/cad39b5f-6f28-4658-8c40-fa0fa51694fd)

其他的问题我自己改掉了，在已经关闭的问题里有，但是还剩这个参考文献的改不掉，我改title函数不管怎么改都报错

**Comment by yuhldr** [comment]
默认没问题，请参考示例：

![图片](https://github.com/user-attachments/assets/3ea8c0ee-7633-4d9c-8a28-f37e8d0df920)

你应该是bib中缺了language = {中文},这一行

![图片](https://github.com/user-attachments/assets/1f9d57a3-cd20-4660-8d4c-f3bb7f0992cf)

**Comment by ffdm12138** [comment]
我超，妙手回春啊大夫，谢谢大佬，我的问题，没注意示例，大写的问题也发现了，把英文再{}扩一下就大写了







-----原始邮件-----
发件人:yuh ***@***.***>
发送时间:2024-12-16 11:27:03 (星期一)
收件人: yuhldr/LZUThesis2020 ***@***.***>
抄送: ffdm12138 ***@***.***>, Author ***@***.***>
主题: [spam]Re: [yuhldr/LZUThesis2020] 中英文混合的参考文献显示不对 (Issue #40)






默认没问题，请参考示例：

default.png (view on web)

你应该是bib中缺了language = {中文},这一行

default.png (view on web)
