### ISSUE TITLE
想问问学长如何使参考文献[num]在右上标1/2处

### ISSUE THREAD

**Issue by cuiry19** [yuhldr/LZUThesis2020#6]
如题，使用您cls里的参考文献语句会使参考文献附在插入处，并且引用字号跟字体大小一样，因为学院的要求，想要把引用的标注放在右上角，1/2字体大小，应该如何设置呢！希望您能够解答，也谢谢您分享的模板！！

**Comment by HollowMan6** [comment]
@cuiry19 

在LZUThesis.cls里增加这两行：
https://github.com/yuhldr/LZUThesis2020/blob/54d35025e09421cdca54bfaa24d3d7a3113c3c96/LZUThesis.cls#L94-L95

然后把你正文里的`\cite{}`都改成`\upcite{}`就行了。

**Comment by yuhldr** [comment]
已经支持 upcite

**Comment by yuhldr** [comment]
> @cuiry19
> 
> 在LZUThesis.cls里增加这两行：
> 
> https://github.com/yuhldr/LZUThesis2020/blob/54d35025e09421cdca54bfaa24d3d7a3113c3c96/LZUThesis.cls#L94-L95
> 
> 然后把你正文里的`\cite{}`都改成`\upcite{}`就行了。

你这个多了个 `textsuperscript` 会偏小
