### ISSUE TITLE
关于2022

### ISSUE THREAD

**Issue by chenyujiehome** [yuhldr/LZUThesis2020#7]
余航学长您好!请问2022本科毕业论文还可以用这个模板吗

**Comment by HollowMan6** [comment]
@JethroChen682 
这个PR应该适配2022最新版了，我目前看的话没有其它啥问题了，如果还有问题的话可以告诉我：https://github.com/yuhldr/LZUThesis2020/pull/13

**Comment by ytf4425** [comment]
> @JethroChen682 这个PR应该适配2022最新版了，我目前看的话没有其它啥问题了，如果还有问题的话可以告诉我：#13

页眉或者标题的段前后磅数有些问题。

模板编译出来的：

<img width="587" alt="image" src="https://user-images.githubusercontent.com/4819825/170530833-28542982-436d-4e96-89af-0c57680730e2.png">

在word中正确设置：

<img width="748" alt="image" src="https://user-images.githubusercontent.com/4819825/170530744-09809d2b-6d06-4fb1-99fb-eebb9b779aa5.png">

规范:

> 章的编号居中，字体为黑体，三号，加粗，居中，单倍行距，段前24磅，段后18磅，如“第一章”；节的编号置顶格，按顺序分层，如“1”，“1.1”，“1.1.1”，层次以少为宜，编号与标题之间空1个字符间隙，如“1.1本科生资料使用”、“1.1.1本科生数据分析”，字体依次为二级标题黑体，四号，顶左，单倍行距，段前24磅，段后6磅；

章到页眉应该是24磅，节到章之间应改为18+24=42磅，因此节到章的间距应该大于顶部间距。

不知这个问题该如何解决？

**Comment by somnuschaplet** [comment]
> > @JethroChen682 这个PR应该适配2022最新版了，我目前看的话没有其它啥问题了，如果还有问题的话可以告诉我：#13
> 
> 页眉或者标题的段前后磅数有些问题。
> 
> 模板编译出来的：
> 
> <img alt="image" width="587" src="https://user-images.githubusercontent.com/4819825/170530833-28542982-436d-4e96-89af-0c57680730e2.png">
> 
> 在word中正确设置：
> 
> <img alt="image" width="748" src="https://user-images.githubusercontent.com/4819825/170530744-09809d2b-6d06-4fb1-99fb-eebb9b779aa5.png">
> 
> 规范:
> 
> > 章的编号居中，字体为黑体，三号，加粗，居中，单倍行距，段前24磅，段后18磅，如“第一章”；节的编号置顶格，按顺序分层，如“1”，“1.1”，“1.1.1”，层次以少为宜，编号与标题之间空1个字符间隙，如“1.1本科生资料使用”、“1.1.1本科生数据分析”，字体依次为二级标题黑体，四号，顶左，单倍行距，段前24磅，段后6磅；
> 
> 章到页眉应该是24磅，节到章之间应改为18+24=42磅，因此节到章的间距应该大于顶部间距。
> 
> @HollowMan6 不知这个问题该如何解决？

是不是他这个章到页眉除了段前的24磅还要算上页边距，所以其实不是24磅。今年新模板里好像应该顶部间距大于节到章的间距。

**Comment by ytf4425** [comment]
@HollowMan6  还有一个神奇的问题，在目录的某一页会出现页码，其他页面没有
<img width="483" alt="image" src="https://user-images.githubusercontent.com/4819825/170663134-5ddd97cb-8ef7-417b-87b3-2463072692d5.png">

**Comment by HollowMan6** [comment]
> 打印出来后量了一下应该是顶部太宽了

@ytf4425 参考这里 https://github.com/ustctug/ustcthesis/issues/102#issuecomment-294344979 设置`chapter/fixskip = true,`可以解决
![image](https://user-images.githubusercontent.com/43995067/170695773-8998e305-900b-4233-bff8-b6bc0c6e80dd.png)

> 还有一个神奇的问题，在目录的某一页会出现页码，其他页面没有

这个问题我报过issue，https://github.com/yuhldr/LZUThesis2020/issues/12

https://github.com/yuhldr/LZUThesis2020/pull/10 这个PR应该就已经解决了，三页目录的话都不会存在问题，不知道你指的是不是应用了我这个PR后还存在问题。如果是的话我这里复现不了，你可以告诉我一下你目录的所占页数。

```tex
%生成目录
\addtocontents{toc}{\protect\thispagestyle{empty}}
\tableofcontents
```

**Comment by ytf4425** [comment]
@HollowMan6 
>参考这里 [ustctug/ustcthesis#102 (comment)](https://github.com/ustctug/ustcthesis/issues/102#issuecomment-294344979) 设置`chapter/fixskip = true,`可以解决 

已设置，上间距确实小了很多，但是上间距还是远大于下间距，不知是段前段后磅数的规则还是仍有问题？

> #10 这个PR应该就已经解决了，三页目录的话都不会存在问题，不知道你指的是不是应用了我这个PR后还存在问题。如果是的话我这里复现不了，你可以告诉我一下你目录的所占页数。

应用了PR之后还存在问题，目录三页，图表目录各一页。

**Comment by HollowMan6** [comment]
@ytf4425 
> 已设置，上间距确实小了很多，但是上间距还是远大于下间距，不知是段前段后磅数的规则还是仍有问题？

![](https://user-images.githubusercontent.com/43995067/170805025-d1ce44fe-1bc3-4693-a5b1-895668c81c0d.png)
本身设置的规则是没问题的，感觉是CTEX的这个BUG还存在。如果有必要的话可以调小这里的数值，你可以试验一下和word等宽时候实际的段前段后值，我就不想搞了（手动狗头）。

> 应用了PR之后还存在问题，目录三页，图表目录各一页。

刚刚这个commit应该修复了，超长目录试验了一下也没问题：https://github.com/yuhldr/LZUThesis2020/pull/10/commits/22b61a3ba6da59d56f6657bdb1e9d3af54d0c913
[template.pdf](https://github.com/yuhldr/LZUThesis2020/files/8790277/template.pdf)

不得不说感觉这又是CTEX的一个BUG。

**Comment by ytf4425** [comment]
> 刚刚这个commit应该修复了，超长目录试验了一下也没问题：https://github.com/yuhldr/LZUThesis2020/commit/22b61a3ba6da59d56f6657bdb1e9d3af54d0c913

目录问题解决，感谢

**Comment by ytf4425** [comment]
> 你可以试验一下和word等宽时候实际的段前段后值，我就不想搞了（手动狗头）。

和word导出的对比了一下，段前没问题了，是段后有点窄了，用了`chapter/fixskip = true`之后好像一级二级标题之间间距也会变小，明天试一下合适的参数
