### ISSUE TITLE
参考文献的title中大写转小写问题解决方法

### ISSUE THREAD

**Issue by HollowMan6** [yuhldr/LZUThesis2020#9]
如直接从百度学术导出下列文献：

```bibtex
@article{陆冰鉴2020基于,
  title={基于EEMD和LSTM的短期风速预测模型研究},
  author={陆冰鉴 and 周鹏 and 王兴 and 周可},
  journal={软件工程},
  number={3},
  pages={43-48},
  year={2020},
}
```

编译后会发现专有名词`EEMD`以及`LSTM`都变为了小写：
![image](https://user-images.githubusercontent.com/43995067/164031043-7b412f58-6b14-40d6-8810-fa91b669dcec.png)

此时给title整体多套一个大括号，即使用如下形式，即可解决问题：

```bibtex
title={{基于EEMD和LSTM的短期风速预测模型研究}},
```

![image](https://user-images.githubusercontent.com/43995067/164032181-d58d7848-ce27-445b-92d1-802a3abdc6b5.png)

**Comment by yuhldr** [comment]
感谢提供，已经加入常见问题
